<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Fixture.Shop.Contracts\Fixture.Shop.Contracts.csproj" />
    <ProjectReference Include="..\Fixture.Shop.Application\Fixture.Shop.Application.csproj" />
    <ProjectReference Include="..\Fixture.Shop.Infrastructure\Fixture.Shop.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
